### ISSUE TITLE
Initial creation of data package

### ISSUE THREAD

**Issue by mradamcox** [healthyregions/oepsData#1]
This ticket is just to get the process started. We'll need an installable data package and at least one table in it.

We'll need at least

- `DESCRIPTION` - use `oepsData` for the package name
- `data-raw/`
- one R script in `data-raw` that loads a CSV of ours and uses `usethis::use_data()` ([see example](https://github.com/Nowosad/spDataLarge/blob/7222dad7c6ecdd786702dc90b2c6509c2614b0cf/data-raw/07_bristol.R#L19)) at least once to spit out a .rda file to `data/`
- make sure it's installable/loadable with
    ```
    devtools::install_github('healthyregions/oepsData')
    library('oepsData')
    ```

Some useful resources for getting started (may be better ones out there, this is just what I've found so far):

- Good overview of concepts and examples: https://www.davekleinschmidt.com/r-packages/#fnref1
- Full walkthrough: https://rstudio4edu.github.io/rstudio4edu-book/data-pkg.html

**Comment by bucketteOfIvy** [comment]
Made the mistake of _not_ including little "#1"'s in my commit messages, but as of commit #5a2a3ce this first step should be done!

**Comment by mradamcox** [comment]
Great! I'm able to install this and preview the table. One warning I'm getting is to use 
```
Warning in person1(given = given[[i]], family = family[[i]], middle = middle[[i]],  :
  It is recommended to use ‘given’ instead of ‘first’.
```
Can you make that update? Then I'd say we can close this ticket and discuss next steps later today.

**Comment by bucketteOfIvy** [comment]
Fixed! (Although I once again forgot to include a little #1 in the commit message..)
