### ISSUE TITLE
some functions are not exported

### ISSUE THREAD

**Issue by ccsarapas** [healthyregions/oepsData#11]
There are a number of functions documented in the package index that aren't exported. eg,
```r
library(oepsData)

state_to_fips("IL")
# Error in state_to_fips("IL") : could not find function "state_to_fips"

county_to_fips(c("Cook", "DuPage"), "17")
# Error in county_to_fips(c("Cook", "DuPage"), "17") :
#   could not find function "county_to_fips"
```
But these work if called with `:::`:
```r
oepsData:::state_to_fips("IL")
# "17"
oepsData:::county_to_fips(c("Cook", "DuPage"), "17")
# "17031" "17043"
```
Are these meant to be exported? (If not, I think you can remove them from the documentation index with the roxygen2 "internal" keyword. But they do seem handy to have user-facing!)

**Comment by bucketteOfIvy** [comment]
They were initially intended to be internal (so the note about roxygen2 having the internal keyword is very useful!), but I'm happy to instead make them user facing. 

Were there any other functions beyond `state_to_fips` and `county_to_fips` that looked like they may be handy?

**Comment by ccsarapas** [comment]
At first glance, I think probably just those two!

**Comment by bucketteOfIvy** [comment]
Awesome -- these should now be exported!

**Comment by mradamcox** [comment]
@ccsarapas I'm thinking we can close this, but can you confirm?

**Comment by ccsarapas** [comment]
Yes, I will close. Thank you!
