### ISSUE TITLE
Remove data with low precision/excessive detail

### ISSUE THREAD

**Issue by Makosak** [healthyregions/oepsData#18]
The following variables were not supposed to be included in the 2.0 version:

- Homelessness variables (due to low precision). Remove completely.
- Details in Jail & Prison variable measures; should include Prison and Jail overall, not disaggregated across multiple groups. These disaggregations should be linked as additional resources that could be pulled from original source, as a note in the documentation.

**Comment by mradamcox** [comment]
Could you clarify by adding the variable names here as well? Just to make sure I don't remove something unintentionally...

**Comment by mradamcox** [comment]
Closed in favor of https://github.com/GeoDaCenter/opioid-policy-scan/issues/165
